services:
  mochi-mqtt:
    image: mochimqtt/server:latest
    container_name: mochi-mqtt
    ports:
      - "${MQTT_BROKER_PORT:-1883}:1883" # MQTT default port
      - "${MQTT_BROKER_WS_PORT:-8000}:8000" # Websocket port
    environment:
      - MOCHI_MQTT_LOG_LEVEL=info
      - MOCHI_MQTT_PORT=${MQTT_BROKER_PORT:-1883}
      - MOCHI_MQTT_WS_PORT=${MQTT_BROKER_WS_PORT:-8000}
    volumes:
      - ./mochi-data:/data
      - ./mochi-mqtt/config.yaml:/config.yaml
    networks:
      - mochi-network
    restart: unless-stopped

  iot-device-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iot-device-manager
    ports:
      - "${API_PORT:-8080}:8080"
    environment:
      - MQTT_BROKER_HOST=mochi-mqtt
      - MQTT_BROKER_PORT=1883
      - API_PORT=${API_PORT:-8080}
    networks:
      - mochi-network
    depends_on:
      - mochi-mqtt

networks:
  mochi-network:
    driver: bridge
